[Interface]
PrivateKey = 6ARXJ15MTbGC5zgG6GT8rEcK+HidlPrsfoNdhgnM6GY=
Address = 10.8.0.13/24
Table = off   

[Peer]
PublicKey = TIPV76Y4f8KOWEgQ7KfpYZOqtmCdCcgkw5mCFiAZsTs=
Endpoint = 158.178.159.108:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
