[Interface]
PrivateKey = OPwPXX97Th0jMU07E2xV0+qXAZ0uiYc7gf4ZJ5lv8nA=
Address = 10.8.0.15/24
Table = off   

[Peer]
PublicKey = TIPV76Y4f8KOWEgQ7KfpYZOqtmCdCcgkw5mCFiAZsTs=
Endpoint = 158.178.159.108:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
