[Interface]
PrivateKey = 0ACi4RRzGGEYT6w5MCj2ly5SQUfJcpPncg2mCixc5HM=
Address = 10.8.0.16/24
Table = off   

[Peer]
PublicKey = TIPV76Y4f8KOWEgQ7KfpYZOqtmCdCcgkw5mCFiAZsTs=
Endpoint = 158.178.159.108:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
