import queue

log_queue = queue.Queue()

COOLDOWNS = {}
CONSECUTIVE_429S = {}
LAST_429_TIME = {}
CONSECUTIVE_RPD_429S = {}
LAST_USED = {}
LAST_REQUEST_TIME = {}

# Compactor statistics
COMPACTOR_ORIG_BYTES = 0
COMPACTOR_COMP_BYTES = 0
COMPACTOR_ORIG_TOKENS = 0
COMPACTOR_COMP_TOKENS = 0
COMPACTOR_SAVED_TOOLS = 0
COMPACTOR_SAVED_SUPERPOWERS = 0
COMPACTOR_SAVED_SKILLS = 0
COMPACTOR_SAVED_DEVCTX = 0
COMPACTOR_SAVED_GENERIC_READ = 0
COMPACTOR_SAVED_REMINDERS = 0
COMPACTOR_INJECTIONS_COUNT = 0
RECENT_ANOMALIES = []
